apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mb9v907w3-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/mb9v907w3-dotnet-basic-gitops